DROP TABLE IF EXISTS order_item   CASCADE;
DROP TABLE IF EXISTS orders       CASCADE;
DROP TABLE IF EXISTS menu         CASCADE;
DROP TABLE IF EXISTS food         CASCADE;
DROP TABLE IF EXISTS teacher      CASCADE;
DROP TABLE IF EXISTS student      CASCADE;
DROP TABLE IF EXISTS department   CASCADE;
